version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/frontend
    ports:
      - '8080:80'
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    environment:
      - PGHOST=db
      - PGDATABASE=sreality_ads
      - PGUSER=postgres
      - PGPASSWORD=charanpostgres
      - PGPORT=5432
    depends_on:
      - db

  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=charanpostgres
      - POSTGRES_DB=sreality_ads
    ports:
      - '5432:5432'
    volumes:
      - ./db-data:/var/lib/postgresql/data
